site_name: R-TYPE
site_url: https://example.com/
nav:
  - Getting Started Guide: index.md
  - Classes: about.md
  - Installation instructions: installation.md
  - License: license.md
  - FAQ: FAQ.md
  - Contact: contact.md
theme: readthedocs